data_ingestion:
  data_original_path: data/stud.csv
  data_train_path: artifacts/data/split_data/train_data.csv
  data_test_path: artifacts/data/split_data/test_data.csv

data_transformation:
  data_target_column: math_score
  data_transformer_path: artifacts/data/transformed_data/data_transformer.pkl
  data_transformed_x_train_array_path: artifacts/data/transformed_data/transformed_x_train_arr.npy
  data_transformed_x_test_array_path: artifacts/data/transformed_data/transformed_x_test_arr.npy
  data_transformed_y_train_array_path: artifacts/data/transformed_data/transformed_y_train_arr.npy
  data_transformed_y_test_array_path: artifacts/data/transformed_data/transformed_y_test_arr.npy
  

model:
  model_trained_path: artifacts/models/trained_model/
  final_model_path: artifacts/models/final_model/model.pkl
  evaluation_metric: r2_score, mean_squared_error, mean_absolute_error
  evaluation_score_json_path: artifacts/models/evaluation_score/scores.json
  evaluation_metric_best_model: mean_squared_error # Can only provide one metric here for best model selection
  mlflow_uri: 